### ISSUE TITLE
Eseguibile in Release

### ISSUE THREAD

**Issue by tiptronic85** [NandayDev/Covid19-Italy-Wpf-Charts#1]
Buongiorno,
potresti gentilmente mettere nella sezione Release, l'eseguibile compilato?
O uno zip.
Grazie

**Comment by NandayDev** [comment]
Ciao! Ho pubblicato due exe, un self-contained (non richiede nessuna dependency) e un framework-dependent (richiede runtime .NET Core 3.1 e .NET Framework)
